title: Vanessa Fiallos # your name (or website title) here
logo: "/images/vf.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an aspiring data analyst with experience in Python and R for data analysis.
  <br><br>
  Completed the Google Data Analytics Certificate Program.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
